{% set name = "sqlacodegen" %}
{% set version = "3.0.0rc3" %}
{% set sha256 = "dbc05fd56e0622abd4f76817c935ca84ae360c538279678263b5b75000b81ccc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - sqlacodegen = sqlacodegen.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools_scm >=6.4
  run:
    - python
    - greenlet >=3.0.0  # [py>=312]
    - importlib_metadata  # [py<310]
    - inflect >=4.0.0
    - sqlalchemy >=1.4.36
  run_constrained:
    - geoalchemy2 >=0.11.1

test:
  imports:
    - sqlacodegen
  commands:
    - sqlacodegen --help

about:
  home: http://pypi.python.org/pypi/sqlacodegen/
  license: MIT
  license_file: LICENSE
  summary: Automatic model code generator for SQLAlchemy
  license_family: MIT

extra:
  recipe-maintainers:
    - rzillman
    - dhirschfeld
